module.exports = [
  {
    word: "adroit",
    phonetic: "/əˈdrɔɪt/",
    definition: "clever or skillful in using the hands or mind; adept at handling situations",
    example: "The negotiator's adroit handling of contentious trade terms averted a costly strike.",
    category: "eloquence",
    synonyms: ["skillful", "dexterous", "adept", "deft"],
    antonyms: ["clumsy", "inept", "maladroit", "gawky"],
    etymology: "from French à droit, properly or rightly, from Latin directus",
    tags: ["business-writing", "everyday-eloquence"]
  },
  {
    word: "affectation",
    phonetic: "/ˌæf.ekˈteɪ.ʃən/",
    definition: "behavior, speech, or writing that is artificial and designed to impress",
    example: "His exaggerated faux-aristocratic accent was an affectation that irritated his colleagues.",
    category: "eloquence",
    synonyms: ["pretension", "posturing", "artifice", "airs"],
    antonyms: ["naturalness", "sincerity", "candor", "simplicity"],
    etymology: "from Latin affectatio, from affectare, to strive after or aim at",
    tags: ["everyday-eloquence", "rhetoric"]
  },
  {
    word: "amplify",
    phonetic: "/ˈæm.plɪ.faɪ/",
    definition: "to enlarge upon or add detail to a story or statement; increase the strength of",
    example: "The keynote speaker took several minutes to amplify her proposal with vivid market case studies.",
    category: "eloquence",
    synonyms: ["expand", "elaborate", "magnify", "augment"],
    antonyms: ["abbreviate", "condense", "attenuate", "curtail"],
    etymology: "from Old French amplifier, from Latin amplificare, to make larger",
    tags: ["rhetoric", "business-writing"]
  },
  {
    word: "anadiplosis",
    phonetic: "/ˌæn.ə.dɪˈpləʊ.sɪs/",
    definition: "repetition of the last word of a preceding clause at the beginning of the next clause",
    example: "The orator declared: 'Strength breeds courage, courage breeds action, action produces triumph.'",
    category: "eloquence",
    synonyms: ["rhetorical doubling", "lexical link", "sequential repetition"],
    antonyms: ["variation", "ellipsis"],
    etymology: "from Greek anadiplosis, doubling back, from ana- (back) + diploun (to double)",
    tags: ["rhetoric"]
  },
  {
    word: "animadversion",
    phonetic: "/ˌæn.ɪ.mædˈvɜː.ʃən/",
    definition: "a comment or remark expressing strong criticism or censure",
    example: "The editorial contained harsh animadversion regarding the ministry's regulatory inertia.",
    category: "eloquence",
    synonyms: ["censure", "criticism", "reproof", "stricture"],
    antonyms: ["praise", "encomium", "eulogy", "tribute"],
    etymology: "from Latin animadversio, noticing with censure, from animadvertere",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "antediluvian",
    phonetic: "/ˌæn.ti.dɪˈluː.vi.ən/",
    definition: "of or belonging to the time before the biblical flood; ridiculously old-fashioned",
    example: "The firm was paralyzed by antediluvian filing systems that required physical carbon paper.",
    category: "eloquence",
    synonyms: ["archaic", "antiquated", "obsolete", "prehistoric"],
    antonyms: ["modern", "cutting-edge", "contemporary", "novel"],
    etymology: "from Latin ante- (before) + diluvium (deluge)",
    tags: ["everyday-eloquence", "GRE"]
  },
  {
    word: "antithetic",
    phonetic: "/ˌæn.tɪˈθet.ɪk/",
    definition: "directly contrasting or opposite in rhetorical balance",
    example: "His speech utilized antithetic clauses to contrast the perils of inaction with the promise of reform.",
    category: "eloquence",
    synonyms: ["contrasting", "counterpoised", "opposed"],
    antonyms: ["parallel", "analogous", "harmonious"],
    etymology: "from Greek antithetikos, from antithesis",
    tags: ["rhetoric"]
  },
  {
    word: "apophasis",
    phonetic: "/əˈpɒf.ə.sɪs/",
    definition: "a rhetorical device wherein the speaker brings up a subject by denying it should be mentioned",
    example: "Using classic apophasis, the candidate said, 'I will not mention my opponent's dubious tax filings.'",
    category: "eloquence",
    synonyms: ["paralipsis", "rhetorical omission", "preterition"],
    antonyms: ["direct declaration", "unambiguous assertion"],
    etymology: "from Greek apophasis, denial, from apophanai, to speak off",
    tags: ["rhetoric"]
  },
  {
    word: "apothegm",
    phonetic: "/ˈæp.ə.θem/",
    definition: "a concise, pithy, and instructive saying; a terse maxim",
    example: "Franklin was celebrated for memorable apothegms such as 'Lost time is never found again.'",
    category: "eloquence",
    synonyms: ["aphorism", "maxim", "adage", "dictum"],
    antonyms: ["platitude", "rambling", "screed", "verbosity"],
    etymology: "from Greek apophthegma, terse utterance, from apophthengesthai, to speak out",
    tags: ["rhetoric", "GRE"],
    confusedWith: [
      { word: "apotheosis", distinction: "An apothegm is a concise, instructive saying; apotheosis is the deification or highest pinnacle of something." }
    ]
  },
  {
    word: "appellation",
    phonetic: "/ˌæp.əˈleɪ.ʃən/",
    definition: "a name or title that identifies a person, place, or entity",
    example: "After twenty successful campaigns, the general earned the proud appellation of 'The Invincible.'",
    category: "eloquence",
    synonyms: ["title", "moniker", "designation", "epithet"],
    antonyms: ["anonymity", "namelessness"],
    etymology: "from Latin appellatio, naming, from appellare, to call upon",
    tags: ["everyday-eloquence", "literary-craft"]
  },
  {
    word: "approbatory",
    phonetic: "/ˈæp.rə.beɪ.tər.i/",
    definition: "expressing formal praise, approval, or commendation",
    example: "The board offered approbatory remarks following the CFO's disciplined balance sheet turnaround.",
    category: "eloquence",
    synonyms: ["commendatory", "complimentary", "laudatory", "approving"],
    antonyms: ["derogatory", "pejorative", "critical", "scornful"],
    etymology: "from Latin approbatus, past participle of approbare",
    tags: ["business-writing", "rhetoric"]
  },
  {
    word: "asseveration",
    phonetic: "/əˌsev.əˈreɪ.ʃən/",
    definition: "the solemn, emphatic declaration or earnest assertion of something",
    example: "Despite the witness's impassioned asseveration, the grand jury demanded physical documentation.",
    category: "eloquence",
    synonyms: ["assertion", "avowal", "protestation", "affirmation"],
    antonyms: ["disavowal", "recantation", "denial", "retraction"],
    etymology: "from Latin asseverare, to assert earnestly",
    tags: ["rhetoric"]
  },
  {
    word: "assonance",
    phonetic: "/ˈæs.ə.nəns/",
    definition: "resemblance of sound between syllables in nearby words, especially identical vowels",
    example: "The poet used rich assonance in 'the light of the fiery night' to mesmerize listeners.",
    category: "eloquence",
    synonyms: ["vowel harmony", "rhyme-likeness", "consonance"],
    antonyms: ["dissonance", "discord", "cacophony"],
    etymology: "from French assonance, from Latin assonare, to respond to sound",
    tags: ["rhetoric", "literary-craft"]
  },
  {
    word: "asyndeton",
    phonetic: "/əˈsɪn.dɪ.tɒn/",
    definition: "the omission or absence of a conjunction between parts of a sentence",
    example: "Caesar's famous dispatch 'I came, I saw, I conquered' is an enduring example of asyndeton.",
    category: "eloquence",
    synonyms: ["omission of connectives", "laconic phrasing"],
    antonyms: ["polysyndeton"],
    etymology: "from Greek asyndetos, unconnected, from a- (not) + syndein (to bind together)",
    tags: ["rhetoric"]
  },
  {
    word: "augury",
    phonetic: "/ˈɔː.ɡjʊ.ri/",
    definition: "a sign of what will happen in the future; an omen or prophetic interpretation",
    example: "The sudden surge in high-yield bond offerings was an augury of growing market risk appetite.",
    category: "eloquence",
    synonyms: ["omen", "portent", "presage", "forewarning"],
    antonyms: ["aftermath", "consequence", "retrospect"],
    etymology: "from Latin augurium, interpretation of omens from bird behavior, from augur",
    tags: ["everyday-eloquence", "literary-craft"]
  },
  {
    word: "avow",
    phonetic: "/əˈvaʊ/",
    definition: "to assert or confess openly, frankly, and without shame",
    example: "The philosopher did not hesitate to avow his skepticism regarding popular theological dogma.",
    category: "eloquence",
    synonyms: ["declare", "profess", "affirm", "acknowledge"],
    antonyms: ["disavow", "repudiate", "renounce", "conceal"],
    etymology: "from Old French avouer, from Latin advocare, to call to witness",
    tags: ["rhetoric", "everyday-eloquence"]
  },
  {
    word: "captious",
    phonetic: "/ˈkæp.ʃəs/",
    definition: "tending to find fault or raise petty objections in argument",
    example: "The editor's captious marginal notes focused on punctuation nuances rather than narrative structure.",
    category: "eloquence",
    synonyms: ["carping", "caviling", "hypercritical", "faultfinding"],
    antonyms: ["forgiving", "complimentary", "magnanimous", "approving"],
    etymology: "from Latin captiosus, fallacious or sophistical, from captio, deception",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "chrestomathy",
    phonetic: "/krɪsˈtɒm.ə.θi/",
    definition: "a collection of selected literary passages or exemplary writings, used for language learning",
    example: "The university press compiled a Latin chrestomathy featuring excerpts from Cicero and Virgil.",
    category: "eloquence",
    synonyms: ["anthology", "compendium", "reader", "selection"],
    antonyms: ["monograph", "treatise", "original draft"],
    etymology: "from Greek khrestomatheia, desire for useful learning, from khrestos (useful) + mathein (to learn)",
    tags: ["rhetoric", "academic-writing"]
  },
  {
    word: "circuitous",
    phonetic: "/sɜːˈkjuː.ɪ.təs/",
    definition: "longer than the most direct way; roundabout in thought, speech, or path",
    example: "He gave a circuitous explanation that avoided answering the reporter's direct inquiry.",
    category: "eloquence",
    synonyms: ["roundabout", "tortuous", "indirect", "meandering"],
    antonyms: ["direct", "straightforward", "linear", "pithy"],
    etymology: "from Medieval Latin circuitosus, from circuitus, a going around",
    tags: ["everyday-eloquence", "rhetoric"]
  },
  {
    word: "compendious",
    phonetic: "/kəmˈpen.di.əs/",
    definition: "containing or presenting the essential facts of a subject in a concise form",
    example: "The lawyer prepared a compendious brief that summarized six years of complex litigation in thirty pages.",
    category: "eloquence",
    synonyms: ["succinct", "terse", "pithy", "condensed"],
    antonyms: ["diffuse", "verbose", "rambling", "voluminous"],
    etymology: "from Latin compendiosus, concise, from compendium, saving or shortcut",
    tags: ["business-writing", "academic-writing"]
  },
  {
    word: "concinnity",
    phonetic: "/kənˈsɪn.ə.ti/",
    definition: "internal harmony, balance, or elegance of style, especially in rhetorical composition",
    example: "The essayist's prose possessed rare concinnity, matching balanced cadence with exact diction.",
    category: "eloquence",
    synonyms: ["elegance", "harmony", "symmetry", "grace"],
    antonyms: ["cacophony", "discord", "incongruity", "clumsiness"],
    etymology: "from Latin concinnitas, neatness, from concinnus, skillfully assembled",
    tags: ["rhetoric", "literary-craft"]
  },
  {
    word: "consuetude",
    phonetic: "/ˈkɒn.swɪ.tjuːd/",
    definition: "customary usage or established social convention, especially when having force of law",
    example: "Generations of parliamentary consuetude dictated the decorum of the chamber.",
    category: "eloquence",
    synonyms: ["tradition", "custom", "convention", "usage"],
    antonyms: ["novelty", "innovation", "disruption", "anomaly"],
    etymology: "from Latin consuetudo, custom or habit, from consuescere, to accustom",
    tags: ["academic-writing", "rhetoric"]
  },
  {
    word: "corroboration",
    phonetic: "/kəˌrɒb.əˈreɪ.ʃən/",
    definition: "evidence that confirms or supports a statement, theory, or finding",
    example: "Independent laboratory testing provided vital corroboration for the chemist's thesis.",
    category: "eloquence",
    synonyms: ["confirmation", "verification", "substantiation", "validation"],
    antonyms: ["refutation", "contradiction", "invalidation", "repudiation"],
    etymology: "from Latin corroborare, to strengthen, from com- + robur (strength)",
    tags: ["business-writing", "academic-writing"]
  },
  {
    word: "declamatory",
    phonetic: "/dɪˈklæm.ə.tər.i/",
    definition: "vehement or impassioned in expression; theatrical and oratorical",
    example: "His declamatory delivery swayed the amphitheater crowd even when his logic fell short.",
    category: "eloquence",
    synonyms: ["oratorical", "rhetorical", "theatrical", "bombastic"],
    antonyms: ["conversational", "understated", "plainspoken", "quiet"],
    etymology: "from Latin declamatorius, from declamare, to make speeches",
    tags: ["rhetoric"]
  },
  {
    word: "deliberative",
    phonetic: "/dɪˈlɪb.ər.ə.tɪv/",
    definition: "relating to or intended for careful consideration or discussion before decision",
    example: "A senate functions best as a deliberative body that shields democracy from hasty impulses.",
    category: "eloquence",
    synonyms: ["thoughtful", "reflective", "consultative", "prudent"],
    antonyms: ["impulsive", "rash", "unconsidered", "precipitous"],
    etymology: "from Latin deliberativus, from deliberare, to weigh well in mind",
    tags: ["rhetoric", "business-writing"]
  },
  {
    word: "dialectical",
    phonetic: "/ˌdaɪ.əˈlek.tɪ.kəl/",
    definition: "relating to the logical discussion of ideas and opinions through debate and thesis confrontation",
    example: "Platonic dialogues demonstrate a dialectical pursuit of truth through iterative questioning.",
    category: "eloquence",
    synonyms: ["argumentative", "discursive", "rational", "analytic"],
    antonyms: ["dogmatic", "oracular", "monological"],
    etymology: "from Greek dialektikos, relating to discussion, from dialegesthai (to converse)",
    tags: ["rhetoric", "academic-writing"]
  },
  {
    word: "disquisition",
    phonetic: "/ˌdɪs.kwɪˈzɪʃ.ən/",
    definition: "a long, elaborate essay or detailed spoken discussion on a particular subject",
    example: "The scholar delivered an exhaustive disquisition on the economic origins of the Peloponnesian War.",
    category: "eloquence",
    synonyms: ["treatise", "dissertation", "exposition", "monograph"],
    antonyms: ["summary", "overview", "synopsis", "aphorism"],
    etymology: "from Latin disquisitio, investigation, from disquirere, to search out thoroughly",
    tags: ["rhetoric", "academic-writing"]
  },
  {
    word: "dissertation",
    phonetic: "/ˌdɪs.əˈteɪ.ʃən/",
    definition: "a long, formal scholarly essay written as partial requirement for a doctorate",
    example: "Her doctoral dissertation on algorithmic fairness was cited by international policy councils.",
    category: "eloquence",
    synonyms: ["thesis", "treatise", "monograph", "disquisition"],
    antonyms: ["abstract", "leaflet", "pamphlet", "outline"],
    etymology: "from Latin dissertatio, from dissertare, to discuss or debate",
    tags: ["academic-writing"]
  },
  {
    word: "elocution",
    phonetic: "/ˌel.əˈkjuː.ʃən/",
    definition: "the skill of clear, expressive, and properly articulated spoken speech",
    example: "Classic theater actors undergo years of voice training in elocution and resonance.",
    category: "eloquence",
    synonyms: ["diction", "articulation", "enunciation", "oratory"],
    antonyms: ["mumbling", "slurring", "inarticulateness", "garbling"],
    etymology: "from Latin elocutio, oratorical delivery, from eloqui, to speak out",
    tags: ["rhetoric"]
  },
  {
    word: "encomiastic",
    phonetic: "/enˌkəʊ.miˈæs.tɪk/",
    definition: "praising enthusiastically in speech or writing; laudatory",
    example: "The retirement banquet opened with an encomiastic tribute praising thirty years of mentorship.",
    category: "eloquence",
    synonyms: ["laudatory", "panegyrical", "complimentary", "acclamatory"],
    antonyms: ["pejorative", "critical", "vitriolic", "derogatory"],
    etymology: "from Greek enkomiastikos, from enkomion, eulogy or praise",
    tags: ["rhetoric", "literary-craft"]
  },
  {
    word: "epanalepsis",
    phonetic: "/ˌep.ə.nəˈlep.sɪs/",
    definition: "a figure of speech where the beginning of a clause is repeated at the end of the same clause",
    example: "The motto 'Mankind must put an end to war, or war will put an end to mankind' demonstrates epanalepsis.",
    category: "eloquence",
    synonyms: ["rhetorical framing", "circular repetition", "bookending"],
    antonyms: ["linear progression", "ellipsis"],
    etymology: "from Greek epanalepsis, repetition, from epi- + ana- + lambanein (to take)",
    tags: ["rhetoric"]
  },
  {
    word: "epistrophe",
    phonetic: "/ɪˈpɪs.trə.fi/",
    definition: "the repetition of a word at the end of successive clauses or sentences",
    example: "Lincoln's 'government of the people, by the people, for the people' is the classic epistrophe.",
    category: "eloquence",
    synonyms: ["antistrophe", "terminal repetition", "concluding echo"],
    antonyms: ["anaphora"],
    etymology: "from Greek epistrophe, turning upon, from epi- (upon) + strephein (to turn)",
    tags: ["rhetoric"],
    confusedWith: [
      { word: "anaphora", distinction: "Epistrophe is repetition of words at the end of sentences; anaphora is repetition at the beginning." }
    ]
  },
  {
    word: "equivoke",
    phonetic: "/ˈek.wɪ.vəʊk/",
    definition: "an ambiguous expression, pun, or double entendre deliberately used to mislead or entertain",
    example: "Shakespeare's fools frequently entertained the court with witty equivoke and playful riddles.",
    category: "eloquence",
    synonyms: ["pun", "quibble", "double entendre", "ambiguity"],
    antonyms: ["plain speech", "univocal statement", "directness"],
    etymology: "from French équivoque, from Late Latin aequivocus",
    tags: ["rhetoric", "literary-craft"]
  },
  {
    word: "euphemism",
    phonetic: "/ˈjuː.fə.mɪz.əm/",
    definition: "a mild or indirect word substituted for one considered too harsh, blunt, or painful",
    example: "Using 'downsizing' as a euphemism for firing hundreds of employees failed to soften the blow.",
    category: "eloquence",
    synonyms: ["polite term", "understatement", "circumlocution", "softening"],
    antonyms: ["dysphemism", "bluntness", "directness", "invective"],
    etymology: "from Greek euphemismos, use of words of good omen, from eu- (good) + pheme (speech)",
    tags: ["rhetoric", "everyday-eloquence"]
  },
  {
    word: "evocative",
    phonetic: "/ɪˈvɒk.ə.tɪv/",
    definition: "bringing strong images, memories, or feelings to mind",
    example: "The author provided an evocative description of rain falling on summer canvas tents.",
    category: "eloquence",
    synonyms: ["reminiscent", "suggestive", "redolent", "expressive"],
    antonyms: ["unimaginative", "dull", "lifeless", "bland"],
    etymology: "from Latin evocativus, from evocare, to call forth",
    tags: ["everyday-eloquence", "literary-craft"]
  },
  {
    word: "exhortation",
    phonetic: "/ˌeɡ.zɔːˈteɪ.ʃən/",
    definition: "an address or communication emphatically urging someone to do something",
    example: "The coach's impassioned halftime exhortation rallied the squad to overcome a two-goal deficit.",
    category: "eloquence",
    synonyms: ["urging", "encouragement", "incitement", "admonition"],
    antonyms: ["discouragement", "deterrent", "dissuasion", "demurral"],
    etymology: "from Latin exhortatio, from exhortari, to encourage earnestly",
    tags: ["rhetoric", "business-writing"]
  },
  {
    word: "expatiate",
    phonetic: "/ɪkˈspeɪ.ʃi.eɪt/",
    definition: "to speak or write at length or in comprehensive detail about a subject",
    example: "The visiting professor expatiated upon sixteenth-century Venetian diplomacy for two hours.",
    category: "eloquence",
    synonyms: ["elaborate", "dilate", "expand", "enlarge"],
    antonyms: ["abbreviate", "summarize", "truncate", "condense"],
    etymology: "from Latin expatiari, to wander out of course, from ex- + spatium (space)",
    tags: ["rhetoric", "GRE"],
    confusedWith: [
      { word: "expiate", distinction: "Expatiate means to speak or write at length; expiate means to atone for guilt or wrongdoing." }
    ]
  },
  {
    word: "fulmination",
    phonetic: "/ˌfʌl.mɪˈneɪ.ʃən/",
    definition: "an expression of vehement protest, condemnation, or wrath",
    example: "The mayor ignored the pundit's daily fulminations and continued with the infrastructure rollout.",
    category: "eloquence",
    synonyms: ["tirade", "diatribe", "denunciation", "screed"],
    antonyms: ["praise", "endorsement", "plaudit", "eulogy"],
    etymology: "from Latin fulminatio, lightning flash, from fulminare, to strike with thunderbolts",
    tags: ["rhetoric"]
  },
  {
    word: "grandiloquence",
    phonetic: "/ɡrænˈdɪl.ə.kwəns/",
    definition: "lofty, pompous, or bombastic language in style or manner",
    example: "His speech was heavy on grandiloquence but strikingly devoid of pragmatic policy commitments.",
    category: "eloquence",
    synonyms: ["bombast", "pomposity", "magniloquence", "orotundity"],
    antonyms: ["simplicity", "plainness", "brevity", "directness"],
    etymology: "from Latin grandiloquus, speaking grandly, from grandis (great) + loqui (to speak)",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "hyperbaton",
    phonetic: "/haɪˈpɜː.bə.tɒn/",
    definition: "an inversion of the normal order of words, especially for emphasis or poetic effect",
    example: "The phrase 'Object there was none; passion there was none' uses hyperbaton for psychological tension.",
    category: "eloquence",
    synonyms: ["inversion", "transposition", "syntactic reversal"],
    antonyms: ["standard word order", "orthodoxy"],
    etymology: "from Greek huperbaton, transposed or stepped over, from huperbainein",
    tags: ["rhetoric"]
  },
  {
    word: "hypophora",
    phonetic: "/haɪˈpɒf.ər.ə/",
    definition: "a figure of speech in which a writer or speaker raises a question and immediately answers it",
    example: "The president asked: 'Can we afford to delay this infrastructure bill? We cannot.'",
    category: "eloquence",
    synonyms: ["question-and-answer device", "rhetorical catechism"],
    antonyms: ["rhetorical question without answer", "soliloquy"],
    etymology: "from Greek hupophora, bringing under or objection, from hupo- + pherein (to carry)",
    tags: ["rhetoric"]
  },
  {
    word: "invective",
    phonetic: "/ɪnˈvek.tɪv/",
    definition: "insulting, abusive, or highly critical language used in denunciation",
    example: "The parliamentary debate deteriorated into partisan invective and personal insults.",
    category: "eloquence",
    synonyms: ["abuse", "vituperation", "vilification", "insult"],
    antonyms: ["praise", "compliment", "accolade", "tribute"],
    etymology: "from Late Latin invectivus, abusive speech, from invehere, to attack with words",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "lucubration",
    phonetic: "/ˌluː.kjʊˈbreɪ.ʃən/",
    definition: "laborious study or writing, especially at night by lamplight; a scholarly discourse",
    example: "The definitive five-volume history was the fruit of forty years of solitary lucubration.",
    category: "eloquence",
    synonyms: ["study", "meditation", "nocturnal toil", "treatise"],
    antonyms: ["improvisation", "spontaneity", "carelessness"],
    etymology: "from Latin lucubratio, work done by lamplight, from lucubrare, to work by night",
    tags: ["academic-writing", "literary-craft"]
  },
  {
    word: "magniloquent",
    phonetic: "/mæɡˈnɪl.ə.kwənt/",
    definition: "using high-flown, bombastic language to impress listeners",
    example: "The defense lawyer delivered a magniloquent address that moved the jury to tears.",
    category: "eloquence",
    synonyms: ["grandiloquent", "pompous", "orotund", "bombastic"],
    antonyms: ["understated", "laconic", "simple", "unadorned"],
    etymology: "from Latin magniloquus, speaking greatly, from magnus (great) + loqui (to speak)",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "paralipsis",
    phonetic: "/ˌpær.əˈlɪp.sɪs/",
    definition: "the rhetorical device of giving emphasis by professing to say nothing about the subject",
    example: "By stating 'I won't dwell on my opponent's repeated ethics investigations,' she executed flawless paralipsis.",
    category: "eloquence",
    synonyms: ["apophasis", "preterition", "feigned omission"],
    antonyms: ["explicit statement", "direct accusation"],
    etymology: "from Greek paraleipsis, leaving aside, from paraleipein, to pass over",
    tags: ["rhetoric"]
  },
  {
    word: "periphrasis",
    phonetic: "/pəˈrɪf.rə.sɪs/",
    definition: "the use of indirect and circumlocutory speech or writing; roundabout phrasing",
    example: "Referring to a car as 'an internal combustion conveyance' is an affected periphrasis.",
    category: "eloquence",
    synonyms: ["circumlocution", "roundabout speech", "pleonasm", "verbiage"],
    antonyms: ["conciseness", "pithiness", "directness", "brevity"],
    etymology: "from Greek periphrasis, roundabout speaking, from peri- (around) + phrazein (to declare)",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "perspicuous",
    phonetic: "/pəˈspɪk.ju.əs/",
    definition: "clearly expressed and easily understood; lucid and transparent in style",
    example: "The judge complimented the young lawyer on her remarkably perspicuous and structured summary.",
    category: "eloquence",
    synonyms: ["lucid", "clear", "transparent", "intelligible"],
    antonyms: ["abstruse", "obscure", "muddy", "incoherent"],
    etymology: "from Latin perspicuus, transparent, from perspicere, to look through",
    tags: ["rhetoric", "business-writing"],
    confusedWith: [
      { word: "perspicacious", distinction: "Perspicuous describes clear, lucid speech or writing; perspicacious describes a person with sharp mental insight." }
    ]
  },
  {
    word: "polysyndeton",
    phonetic: "/ˌpɒl.iˈsɪn.dɪ.tɒn/",
    definition: "the deliberate repetition of conjunctions in close succession for rhythmic urgency",
    example: "The witness declared: 'There were sirens and shouting and running and total pandemonium.'",
    category: "eloquence",
    synonyms: ["conjunction repetition", "additive cadence"],
    antonyms: ["asyndeton"],
    etymology: "from Greek polusyndetos, bound together with many conjunctions, from polus (many) + syndein",
    tags: ["rhetoric"]
  },
  {
    word: "pleonasm",
    phonetic: "/ˈpliː.ə.næz.əm/",
    definition: "the use of more words than are necessary to convey meaning, as in 'see with one's own eyes'",
    example: "The editor highlighted the phrase 'burning fire' as an avoidable pleonasm in the manuscript.",
    category: "eloquence",
    synonyms: ["redundancy", "tautology", "verbiage", "superfluity"],
    antonyms: ["conciseness", "laconicism", "pithiness", "brevity"],
    etymology: "from Greek pleonasmos, excess, from pleonazein, to be more than enough",
    tags: ["rhetoric", "GRE"]
  },
  {
    word: "zeugma",
    phonetic: "/ˈzjuːɡ.mə/",
    definition: "a figure of speech in which a word applies to two others in different senses",
    example: "In Dickens' famous line, the gentleman 'took his hat and his leave.'",
    category: "eloquence",
    synonyms: ["syllepsis", "semantic coupling", "yoked phrasing"],
    antonyms: ["parallelism", "literal phrasing"],
    etymology: "from Greek zeugma, yoking or bond, from zeugnunai, to yoke",
    tags: ["rhetoric", "literary-craft"]
  }
];
