module.exports = [
  {
    word: "alpenglow",
    phonetic: "/ˈæl.pən.ɡləʊ/",
    definition: "the rosy or reddish optical glow seen near sunset or sunrise on the summits of mountains",
    example: "We stood mesmerized as the alpenglow transformed the jagged granite peaks into burning copper.",
    category: "literary",
    synonyms: ["rosy glow", "afterglow", "mountain luminescence", "dawn light"],
    antonyms: ["darkness", "shadow", "gloom", "murk"],
    etymology: "from German Alpenglühen, from Alpen (Alps) + glühen (to glow)",
    tags: ["literary-craft"],
    confusedWith: [
      { word: "afterglow", distinction: "Alpenglow refers specifically to light on mountain summits, whereas afterglow can describe any sky illumination after sunset." }
    ]
  },
  {
    word: "amethystine",
    phonetic: "/ˌæm.əˈθɪs.taɪn/",
    definition: "resembling or possessing the deep violet-purple tint of amethyst quartz",
    example: "The evening tide rolled across the estuary in rich amethystine shadows under the violet sky.",
    category: "literary",
    synonyms: ["violet", "purplish", "lavender", "plum"],
    antonyms: ["colorless", "pale", "ashen", "bleached"],
    etymology: "from Greek amethystinos, from amethystos, not drunken (believed to prevent intoxication)",
    tags: ["literary-craft"]
  },
  {
    word: "atramentous",
    phonetic: "/ˌæt.rəˈmen.təs/",
    definition: "as black as ink; deep, impenetrable darkness",
    example: "The submarine sank into the atramentous abyss of the oceanic trench where no sunlight reaches.",
    category: "literary",
    synonyms: ["inky", "pitch-black", "ebon", "sooty"],
    antonyms: ["luminous", "radiant", "alabaster", "bright"],
    etymology: "from Latin atramentum, black ink, from ater, dull black",
    tags: ["literary-craft"]
  },
  {
    word: "auroral",
    phonetic: "/ɔːˈrɔː.rəl/",
    definition: "pertaining to or resembling the dawn or the aurora borealis; luminous and roseate",
    example: "An auroral shimmer swept across the northern horizon in ribbons of emerald and magenta.",
    category: "literary",
    synonyms: ["dawn-like", "luminescent", "roseate", "shimmering"],
    antonyms: ["nocturnal", "dim", "crepuscular", "dark"],
    etymology: "from Latin Aurora, Roman goddess of the dawn",
    tags: ["literary-craft"]
  },
  {
    word: "balm",
    phonetic: "/bɑːm/",
    definition: "a soothing, fragrant substance or comforting agency that heals grief or pain",
    example: "Her thoughtful letter arrived like a gentle balm upon a wounded and weary spirit.",
    category: "literary",
    synonyms: ["solace", "salve", "consolation", "anodyne"],
    antonyms: ["irritant", "affliction", "torment", "curse"],
    etymology: "from Old French basme, through Latin from Greek balsamon",
    tags: ["literary-craft", "everyday-eloquence"]
  },
  {
    word: "caducous",
    phonetic: "/kəˈdjuː.kəs/",
    definition: "easily detached and shedding at an early stage; ephemeral or transient in nature",
    example: "Autumn winds swept away the caducous foliage of the ancient birch groves.",
    category: "literary",
    synonyms: ["shedding", "deciduous", "fugitive", "evanescent"],
    antonyms: ["persistent", "perennial", "evergreen", "abiding"],
    etymology: "from Latin caducus, falling, from cadere, to fall",
    tags: ["literary-craft"]
  },
  {
    word: "canticle",
    phonetic: "/ˈkæn.tɪ.kəl/",
    definition: "a hymn, psalm, or lyrical chant taken from a biblical text or poetic scripture",
    example: "At vespers, the choristers sang an ancient canticle that echoed off the vaulted nave.",
    category: "literary",
    synonyms: ["hymn", "chant", "song", "anthem"],
    antonyms: ["dirge", "silence", "screed", "invective"],
    etymology: "from Latin canticulum, little song, diminutive of canticum",
    tags: ["literary-craft"]
  },
  {
    word: "cerulean",
    phonetic: "/sɪˈruː.li.ən/",
    definition: "deep, clear sky blue; resembling the radiant dome of heaven",
    example: "The sailboat drifted across the calm, cerulean expanse of the Aegean Sea.",
    category: "literary",
    synonyms: ["azure", "sky-blue", "sapphire", "cyan"],
    antonyms: ["somber", "muddy", "leaden", "turbid"],
    etymology: "from Latin caeruleus, dark blue or sky-blue, from caelum, sky or heaven",
    tags: ["literary-craft"]
  },
  {
    word: "cimmerian",
    phonetic: "/sɪˈmɪə.ri.ən/",
    definition: "very dark, gloomy, and shrouded in perpetual fog or shadow",
    example: "The traveler plunged into the cimmerian gloom of the uncharted subterranean caverns.",
    category: "literary",
    synonyms: ["tenebrous", "gloomy", "murky", "shadowy"],
    antonyms: ["sunlit", "luminous", "brilliant", "diaphanous"],
    etymology: "from the Cimmerii, a mythical people described by Homer as living in perpetual mists",
    tags: ["literary-craft"]
  },
  {
    word: "coruscate",
    phonetic: "/ˈkɒr.ə.skeɪt/",
    definition: "to flash or sparkle brightly; exhibit brilliant flashes of light or wit",
    example: "Diamond droplets of melting frost coruscated beneath the crisp morning sun.",
    category: "literary",
    synonyms: ["scintillate", "sparkle", "glisten", "flash"],
    antonyms: ["smolder", "darken", "fade", "dull"],
    etymology: "from Latin coruscare, to vibrate, quiver, or flash",
    tags: ["literary-craft"]
  },
  {
    word: "craquelure",
    phonetic: "/krækˈlʊər/",
    definition: "a network of fine cracks on the surface of an old painting or ceramic glaze",
    example: "The conservator examined the fine craquelure spidering across the portrait's varnished face.",
    category: "literary",
    synonyms: ["crazing", "cracking", "fissuring", "patina"],
    antonyms: ["smoothness", "flawlessness", "gloss", "polish"],
    etymology: "from French craqueler, to crackle, of imitative origin",
    tags: ["literary-craft"]
  },
  {
    word: "deliquesce",
    phonetic: "/ˌdel.ɪˈkwes/",
    definition: "to dissolve gradually into liquid by absorbing moisture, or melt away softly",
    example: "The morning fog began to deliquesce under the rising heat of the midsummer sun.",
    category: "literary",
    synonyms: ["liquefy", "melt", "dissolve", "thaw"],
    antonyms: ["solidify", "crystallize", "congeal", "coagulate"],
    etymology: "from Latin deliquescere, to melt away, from de- (down) + liquere (to be liquid)",
    tags: ["literary-craft"]
  },
  {
    word: "eburnean",
    phonetic: "/ɪˈbɜː.ni.ən/",
    definition: "resembling or made of ivory; smooth, creamy white",
    example: "The moonlight revealed an eburnean shoreline of polished shells and chalk cliffs.",
    category: "literary",
    synonyms: ["ivory", "alabaster", "cream-colored", "pearly"],
    antonyms: ["jet-black", "dusky", "sooty", "charcoal"],
    etymology: "from Latin eburneus, of ivory, from ebur, ivory",
    tags: ["literary-craft"]
  },
  {
    word: "efflorescence",
    phonetic: "/ˌef.ləˈres.əns/",
    definition: "the state or period of flowering; the ultimate blooming culmination of artistic growth",
    example: "The city experienced a marvelous cultural efflorescence during the decades of peace.",
    category: "literary",
    synonyms: ["blooming", "flowering", "zenith", "blossoming"],
    antonyms: ["decay", "wither", "stagnation", "decline"],
    etymology: "from Latin efflorescere, to burst into flower, from ex- (out) + florescere (to blossom)",
    tags: ["literary-craft"]
  },
  {
    word: "effulgent",
    phonetic: "/ɪˈfʌl.dʒənt/",
    definition: "shining forth brilliantly; radiant and resplendent",
    example: "The cathedral was bathed in effulgent golden beams streaming through stained glass.",
    category: "literary",
    synonyms: ["radiant", "incandescent", "dazzling", "lustrous"],
    antonyms: ["dim", "somber", "clouded", "murky"],
    etymology: "from Latin effulgere, to shine forth, from ex- (out) + fulgere (to shine)",
    tags: ["literary-craft"]
  },
  {
    word: "eldritch",
    phonetic: "/ˈel.drɪtʃ/",
    definition: "weird, eerie, and unearthly; inspiring uncanny dread",
    example: "An eldritch screech echoed through the abandoned ruins at the edge of the swamp.",
    category: "literary",
    synonyms: ["uncanny", "spectral", "unearthly", "ghostly"],
    antonyms: ["mundane", "familiar", "natural", "wholesome"],
    etymology: "from Middle English elf-riche, fairy kingdom, hence ghostly and unnatural",
    tags: ["literary-craft"]
  },
  {
    word: "elysian",
    phonetic: "/ɪˈlɪz.i.ən/",
    definition: "relating to Elysium; blissful, delightful, and divinely peaceful",
    example: "The travelers lounged in elysian contentment along the pristine Mediterranean grove.",
    category: "literary",
    synonyms: ["heavenly", "paradisiacal", "blissful", "serene"],
    antonyms: ["infernal", "tormented", "wretched", "abyssal"],
    etymology: "from Greek Elysion, the mythical island dwelling of the blessed spirits",
    tags: ["literary-craft"]
  },
  {
    word: "embrocation",
    phonetic: "/ˌem.brəˈkeɪ.ʃən/",
    definition: "a lotion or liquid preparation used for rubbing onto the body to soothe aches",
    example: "The herbalist blended camphor and wintergreen into an aromatic embrocation for sore muscles.",
    category: "literary",
    synonyms: ["liniment", "ointment", "lotion", "salve"],
    antonyms: ["abrasive", "caustic", "irritant", "poison"],
    etymology: "from Medieval Latin embrocatio, from Greek embroche, moistening lotion",
    tags: ["literary-craft"]
  },
  {
    word: "empyrean",
    phonetic: "/ˌem.paɪˈriː.ən/",
    definition: "relating to heaven or the highest celestial sphere of pure light and fire",
    example: "Stargazers marveled at the empyrean heights where nebulae spun in silent grandeur.",
    category: "literary",
    synonyms: ["celestial", "heavenly", "ethereal", "sublime"],
    antonyms: ["terrestrial", "earthly", "subterranean", "mundane"],
    etymology: "from Greek empyrios, in or on the fire, referring to the fiery highest heaven",
    tags: ["literary-craft"]
  },
  {
    word: "evanesce",
    phonetic: "/ˌev.əˈnes/",
    definition: "to pass out of sight, memory, or existence; fade away like vapor",
    example: "The ghost ship seemed to evanesce into the thick ocean mist before our eyes.",
    category: "literary",
    synonyms: ["vanish", "dissolve", "fade", "dissipate"],
    antonyms: ["materialize", "appear", "endure", "persist"],
    etymology: "from Latin evanescere, from ex- (out) + vanus (empty)",
    tags: ["literary-craft"]
  },
  {
    word: "febrile",
    phonetic: "/ˈfeɪ.braɪl/",
    definition: "having or showing the symptoms of a fever; characterized by nervous excitement or agitation",
    example: "A febrile tension gripped the city as the decisive election results trickled in.",
    category: "literary",
    synonyms: ["feverish", "frenetic", "hectic", "impassioned"],
    antonyms: ["placid", "calm", "serene", "tranquil"],
    etymology: "from Latin febrilis, from febris, fever",
    tags: ["literary-craft", "academic-writing"]
  },
  {
    word: "flâneur",
    phonetic: "/flæˈnɜːr/",
    definition: "an idle stroller, observer, or wanderer who contemplates society amidst the city streets",
    example: "As a quintessential flâneur, the poet spent afternoons strolling Paris without destination.",
    category: "literary",
    synonyms: ["stroller", "saunterer", "bystander", "boulevardier"],
    antonyms: ["drudge", "laborer", "commuter", "worker"],
    etymology: "from French flâneur, from flâner, to stroll or lounge leisurely",
    tags: ["literary-craft"]
  },
  {
    word: "fulgent",
    phonetic: "/ˈfʌl.dʒənt/",
    definition: "shining brightly; dazzling and radiant",
    example: "The coronation crown stood out against dark velvet with fulgent emeralds and diamonds.",
    category: "literary",
    synonyms: ["brilliant", "gleaming", "scintillating", "radiant"],
    antonyms: ["dim", "lackluster", "murky", "dull"],
    etymology: "from Latin fulgere, to flash or shine",
    tags: ["literary-craft"]
  },
  {
    word: "fuscous",
    phonetic: "/ˈfʌs.kəs/",
    definition: "of a dark, somber, brownish-gray color",
    example: "The moth rested upon the tree trunk, its fuscous wings blending into the decaying bark.",
    category: "literary",
    synonyms: ["dusky", "brownish-gray", "tawny", "swarthy"],
    antonyms: ["gleaming", "vibrant", "niveous", "iridescent"],
    etymology: "from Latin fuscus, dark, swarthy, or dim",
    tags: ["literary-craft"]
  },
  {
    word: "glaucous",
    phonetic: "/ˈɡlɔː.kəs/",
    definition: "of a dull grayish-green or bluish-green color, often with a powdery bloom",
    example: "The glaucous foliage of eucalyptus trees swayed gracefully in the salt sea breeze.",
    category: "literary",
    synonyms: ["sea-green", "blue-gray", "sage", "frosted"],
    antonyms: ["crimson", "golden", "glossy", "jet"],
    etymology: "from Greek glaukos, bluish-gray or gleaming green",
    tags: ["literary-craft"]
  },
  {
    word: "gloaming",
    phonetic: "/ˈɡləʊ.mɪŋ/",
    definition: "twilight or dusk; the period of fading light between sunset and full dark",
    example: "Bats fluttered overhead through the purple gloaming as day slipped into quiet night.",
    category: "literary",
    synonyms: ["twilight", "dusk", "nightfall", "crepuscule"],
    antonyms: ["dawn", "daybreak", "sunrise", "noon"],
    etymology: "from Old English glōmung, twilight, related to glōwian, to glow",
    tags: ["literary-craft"]
  },
  {
    word: "hiraeth",
    phonetic: "/ˈhɪə.raɪθ/",
    definition: "a deep, wistful homesickness for a home or past era to which one cannot return",
    example: "Hearing the traditional ballad evoked a profound sense of hiraeth in the aging emigrant.",
    category: "literary",
    synonyms: ["yearning", "nostalgia", "homesickness", "wistfulness"],
    antonyms: ["contentment", "indifference", "satisfaction", "belonging"],
    etymology: "from Welsh hiraeth, longing or homesickness",
    tags: ["literary-craft"]
  },
  {
    word: "imbue",
    phonetic: "/ɪmˈbjuː/",
    definition: "to inspire or permeate with a feeling, quality, or conviction; saturate with color",
    example: "Her grandfather's stories served to imbue her imagination with a love of historical adventure.",
    category: "literary",
    synonyms: ["infuse", "instill", "saturate", "permeate"],
    antonyms: ["drain", "divest", "strip", "purge"],
    etymology: "from Latin imbuere, to moisten, dip, or stain",
    tags: ["literary-craft", "everyday-eloquence"]
  },
  {
    word: "incarnadine",
    phonetic: "/ɪnˈkɑː.nə.daɪn/",
    definition: "a bright crimson or pinkish-red color; to turn blood-red",
    example: "The dying sunset seemed to incarnadine the white crests of the restless ocean waves.",
    category: "literary",
    synonyms: ["crimson", "blood-red", "ruby", "carmine"],
    antonyms: ["pale", "ashen", "pallid", "blanched"],
    etymology: "from Italian incarnadino, flesh color, from Latin caro, flesh",
    tags: ["literary-craft"]
  },
  {
    word: "inflorescence",
    phonetic: "/ˌɪn.fləˈres.əns/",
    definition: "the complete flower head of a plant including stems, stalks, and blossoms",
    example: "The rare alpine orchid produced a magnificent inflorescence of delicate lavender bells.",
    category: "literary",
    synonyms: ["blossoming", "cluster", "bloom", "floral arrangement"],
    antonyms: ["withering", "defoliation", "decay", "barrenness"],
    etymology: "from Late Latin inflorescere, to begin to blossom",
    tags: ["literary-craft"]
  },
  {
    word: "lambent",
    phonetic: "/ˈlæm.bənt/",
    definition: "running or playing on a surface without burning; softly bright, flickering, or radiant",
    example: "The candle cast a lambent glow across the open pages of the leather-bound diary.",
    category: "literary",
    synonyms: ["flickering", "luminous", "glowing", "shimmering"],
    antonyms: ["blazing", "scorching", "dark", "extinguished"],
    etymology: "from Latin lambere, to lick or lap gently",
    tags: ["literary-craft"]
  },
  {
    word: "lissome",
    phonetic: "/ˈlɪs.əm/",
    definition: "thin, supple, and graceful in body movement; lithe",
    example: "The lissome ballerina moved across the stage as effortlessly as a falling feather.",
    category: "literary",
    synonyms: ["lithe", "supple", "nimble", "graceful"],
    antonyms: ["stiff", "clumsy", "awkward", "rigid"],
    etymology: "variant of lithesome, from Old English līthe, gentle or flexible",
    tags: ["literary-craft"]
  },
  {
    word: "lustral",
    phonetic: "/ˈlʌs.trəl/",
    definition: "relating to or used in ceremonial purification or cleansing",
    example: "Pilgrims washed their hands in the lustral waters of the mountain spring before prayer.",
    category: "literary",
    synonyms: ["purificatory", "cleansing", "sacramental", "sanctifying"],
    antonyms: ["polluting", "defiling", "tainting", "contaminating"],
    etymology: "from Latin lustralis, from lustrum, purificatory sacrifice",
    tags: ["literary-craft"]
  },
  {
    word: "marmoreal",
    phonetic: "/mɑːˈmɔː.ri.əl/",
    definition: "resembling marble, especially in coldness, smoothness, or pale stillness",
    example: "The aristocrat possessed a marmoreal calm that revealed no emotional tremor.",
    category: "literary",
    synonyms: ["marble-like", "statuesque", "cold", "impassive"],
    antonyms: ["expressive", "warm", "animated", "pliable"],
    etymology: "from Latin marmoreus, from marmor, marble",
    tags: ["literary-craft"]
  },
  {
    word: "nescience",
    phonetic: "/ˈneʃ.əns/",
    definition: "lack of knowledge or awareness; profound ignorance",
    example: "Ancient maps reflected complete nescience concerning the lands beyond the western sea.",
    category: "literary",
    synonyms: ["ignorance", "unawareness", "innocence", "benightedness"],
    antonyms: ["omniscience", "erudition", "knowledge", "wisdom"],
    etymology: "from Late Latin nescientia, from nescire, not to know",
    tags: ["literary-craft", "academic-writing"]
  },
  {
    word: "niveous",
    phonetic: "/ˈnɪv.i.əs/",
    definition: "resembling snow; snowy white",
    example: "A solitary swan floated serenely upon the pond, its niveous plumage pristine.",
    category: "literary",
    synonyms: ["snowy", "alabaster", "chalky", "milky"],
    antonyms: ["fuscous", "charcoal", "dusky", "sooty"],
    etymology: "from Latin niveus, from nix (genitive nivis), snow",
    tags: ["literary-craft"]
  },
  {
    word: "noctilucent",
    phonetic: "/ˌnɒk.tɪˈluː.sənt/",
    definition: "shining or glowing during the night; phosphorescent clouds high in the atmosphere",
    example: "In Scandinavian midsummer, delicate noctilucent clouds shone silvery against the twilight sky.",
    category: "literary",
    synonyms: ["phosphorescent", "night-shining", "luminescent", "glowing"],
    antonyms: ["dark", "shadowy", "obscure", "opaque"],
    etymology: "from Latin nox (night) + lucere (to shine)",
    tags: ["literary-craft"]
  },
  {
    word: "nyctophilia",
    phonetic: "/ˌnɪk.təˈfɪl.i.ə/",
    definition: "a preference for the night or darkness; comfort found in the dark hours",
    example: "His lifelong nyctophilia made late-night stargazing and solitary writing his greatest joy.",
    category: "literary",
    synonyms: ["night-loving", "nocturnal affinity", "darkness affinity"],
    antonyms: ["photophilia", "heliophilia", "sun-craving"],
    etymology: "from Greek nyx (night) + philia (love)",
    tags: ["literary-craft"]
  },
  {
    word: "obmutescence",
    phonetic: "/ˌɒb.mjuːˈtes.əns/",
    definition: "a stubborn, persistent, or solemn silence; refusal to speak",
    example: "Confronted by the magistrates, the captive maintained an unyielding obmutescence.",
    category: "literary",
    synonyms: ["silence", "muteness", "taciturnity", "speechlessness"],
    antonyms: ["loquacity", "volubility", "outspokenness", "clamor"],
    etymology: "from Latin obmutescere, to become mute, from ob- + mutus (mute)",
    tags: ["literary-craft"]
  },
  {
    word: "oneiric",
    phonetic: "/oʊˈnaɪ.rɪk/",
    definition: "relating to dreams or dreaming; possessing a surreal, dreamlike quality",
    example: "The director's film possessed an oneiric rhythm where past and present flowed seamlessly.",
    category: "literary",
    synonyms: ["dreamlike", "surreal", "phantasmagoric", "visionary"],
    antonyms: ["realistic", "literal", "prosaic", "pragmatic"],
    etymology: "from Greek oneiros, dream",
    tags: ["literary-craft"]
  },
  {
    word: "opalescent",
    phonetic: "/ˌəʊ.pəˈles.ənt/",
    definition: "showing varying colors as an opal does; iridescent and shimmering",
    example: "The interior of the abalone shell revealed an opalescent swirl of pastel hues.",
    category: "literary",
    synonyms: ["iridescent", "pearly", "prismatic", "shimmering"],
    antonyms: ["matte", "dull", "monochromatic", "drab"],
    etymology: "from opal + -escent, from Latin opalus",
    tags: ["literary-craft"]
  },
  {
    word: "orgulous",
    phonetic: "/ˈɔː.ɡjʊ.ləs/",
    definition: "haughty, proud, and disdainful",
    example: "The orgulous baron refused to seat himself among the merchant guild representatives.",
    category: "literary",
    synonyms: ["haughty", "arrogant", "supercilious", "proud"],
    antonyms: ["humble", "modest", "meek", "unassuming"],
    etymology: "from Old French orguillus, from orgueil, pride",
    tags: ["literary-craft"]
  },
  {
    word: "peregrination",
    phonetic: "/ˌper.ə.ɡrɪˈneɪ.ʃən/",
    definition: "a long, winding journey, especially on foot or to distant foreign lands",
    example: "His youth was spent in restless peregrination across the ports and deserts of the Levant.",
    category: "literary",
    synonyms: ["journey", "wanderings", "voyage", "odyssey"],
    antonyms: ["residence", "stationarity", "settlement", "fixity"],
    etymology: "from Latin peregrinatio, travel abroad, from peregrinari, to sojourn away from home",
    tags: ["literary-craft"]
  },
  {
    word: "psithurism",
    phonetic: "/ˈsɪθ.jʊ.rɪz.əm/",
    definition: "the sound of wind whispering softly through the leaves of trees",
    example: "Lying beneath the tall pines, she was lulled to sleep by the tranquil psithurism above.",
    category: "literary",
    synonyms: ["rustling", "whispering foliage", "susurrus", "wind-murmur"],
    antonyms: ["silence", "stillness", "roar", "clamor"],
    etymology: "from Greek psithurisma, whisper, from psithuros, whispering",
    tags: ["literary-craft"]
  },
  {
    word: "purpureal",
    phonetic: "/pɜːˈpjʊə.ri.əl/",
    definition: "of or pertaining to the color purple; imperial, majestic, and regal",
    example: "The emperor donned a purpureal mantle embroidered with gold constellations.",
    category: "literary",
    synonyms: ["purple", "regal", "imperial", "violet"],
    antonyms: ["drab", "modest", "humble", "colorless"],
    etymology: "from Latin purpureus, from purpura, purple dye extracted from murex snails",
    tags: ["literary-craft"]
  },
  {
    word: "refulgent",
    phonetic: "/rɪˈfʌl.dʒənt/",
    definition: "shining brightly; radiant and gleaming with dazzling splendor",
    example: "The chandeliers bathed the grand ballroom in a refulgent cascade of golden light.",
    category: "literary",
    synonyms: ["radiant", "effulgent", "brilliant", "lustrous"],
    antonyms: ["dim", "lackluster", "shadowy", "tarnished"],
    etymology: "from Latin refulgere, to flash back or shine brightly",
    tags: ["literary-craft"]
  },
  {
    word: "riparian",
    phonetic: "/raɪˈpeə.ri.ən/",
    definition: "relating to or situated on the banks of a river or natural stream",
    example: "The riparian corridor sustained hundreds of migratory songbirds and lush willow thickets.",
    category: "literary",
    synonyms: ["riverbank", "fluvial", "waterside", "bankside"],
    antonyms: ["arid", "desert", "upland", "pelagic"],
    etymology: "from Latin riparius, from ripa, river bank",
    tags: ["literary-craft", "academic-writing"]
  },
  {
    word: "sciamachy",
    phonetic: "/saɪˈæm.ə.ki/",
    definition: "a battle or contest against shadows, or against imaginary or nonexistent enemies",
    example: "Obsessed with conspiracy theories, the senator engaged in an endless political sciamachy.",
    category: "literary",
    synonyms: ["shadow-boxing", "tilting at windmills", "imaginary combat"],
    antonyms: ["real battle", "substantive engagement", "factual contest"],
    etymology: "from Greek skiamakhia, from skia (shadow) + makhe (battle)",
    tags: ["literary-craft"]
  },
  {
    word: "telluric",
    phonetic: "/teˈljʊə.rɪk/",
    definition: "of the earth or soil; terrestrial or coming from deep beneath the ground",
    example: "Earthquake tremors unleashed powerful telluric currents detected by seismographs.",
    category: "literary",
    synonyms: ["terrestrial", "earthly", "geological", "subterranean"],
    antonyms: ["celestial", "aerial", "heavenly", "atmospheric"],
    etymology: "from Latin tellus (genitive telluris), earth",
    tags: ["literary-craft", "academic-writing"]
  },
  {
    word: "viridian",
    phonetic: "/vɪˈrɪd.i.ən/",
    definition: "a bluish-green pigment or vibrant dark green color",
    example: "Ferns and moss spread like a plush viridian carpet across the forest floor.",
    category: "literary",
    synonyms: ["blue-green", "emerald", "teal", "verdant"],
    antonyms: ["russet", "amber", "crimson", "bleached"],
    etymology: "from Latin viridis, green, from virere, to be verdant",
    tags: ["literary-craft"]
  }
];
